### ISSUE TITLE
different n_units in hidden layers

### ISSUE THREAD

**Issue by xuhongzuo** [jshi31/Jacobian_of_MLP#1]
It is an impressive implementation of calculating Jacobian matrix. I am wondering whether it is possible to support MLP when hidden layers are with different units? Thanks.

**Comment by xwqok** [comment]
Are you referring to hidden units in different dimensions？I think just modify the corresponding nn.sequenti module and it will be work.

**Comment by xwqtju** [comment]
> It is an impressive implementation of calculating Jacobian matrix. I am wondering whether it is possible to support MLP when hidden layers are with different units? Thanks.

Are you referring to hidden units in different dimensions？I think just modify the corresponding nn.sequenti module and it will be work. I have also recently been concerned with the calculation of jacobian matrices for neural networks

**Comment by xuhongzuo** [comment]
I just found my question is unclear. I mean hidden layers are with different numbers of units.

Yes, It is easy to modify the initialization function. But the last line of the "jacobian" function is `J = Delta @ W.unsqueeze(0).expand(bs, self.n_units, self.n_inputs)`. I am not sure how to assign `self.n_units` here if hidden layers are with different numbers of units. It seems that this variable should be the dimension of the first hidden layer?
Thanks for sharing.

**Comment by xwqtju** [comment]
> I just found my question is unclear. I mean hidden layers are with different numbers of units.
> 
> Yes, It is easy to modify the initialization function. But the last line of the "jacobian" function is `J = Delta @ W.unsqueeze(0).expand(bs, self.n_units, self.n_inputs)`. I am not sure how to assign `self.n_units` here if hidden layers are with different numbers of units. It seems that this variable should be the dimension of the first hidden layer? Thanks for sharing.

You're right, I also think that self.n_units that appears on the last line of the "jacobian" function should be the dimension of the first hidden layer. So if there are different units, I think it should give a list of hidden layers `n_units = [C1, C2... Cn]`, and take the derivative by reverse chain, `J = Delta @w.unsqueeze (0). expand (bs, self.n_units[0], self.n_inputs)`.
And，the initialization should be modified as:
```
        layers = [nn.Linear(n_inputs, n_units[0])]
        for i in range(n_layers-1):
            layers.append(nonlinear())
            layers.append(nn.Linear(n_units[i], n_units[i+1]))
        layers.append(nonlinear())
        layers.append(nn.Linear(n_units[-1], n_outputs))
        self.layers = nn.Sequential(*layers)
```

**Comment by xuhongzuo** [comment]
That's Cool. I really appreciate it.

**Comment by xuhongzuo** [comment]
> > I just found my question is unclear. I mean hidden layers are with different numbers of units.
> > Yes, It is easy to modify the initialization function. But the last line of the "jacobian" function is `J = Delta @ W.unsqueeze(0).expand(bs, self.n_units, self.n_inputs)`. I am not sure how to assign `self.n_units` here if hidden layers are with different numbers of units. It seems that this variable should be the dimension of the first hidden layer? Thanks for sharing.
> 
> You're right, I also think that self.n_units that appears on the last line of the "jacobian" function should be the dimension of the first hidden layer. So if there are different units, I think it should give a list of hidden layers `n_units = [C1, C2... Cn]`, and take the derivative by reverse chain, `J = Delta @w.unsqueeze (0). expand (bs, self.n_units[0], self.n_inputs)`. And，the initialization should be modified as:
> 
> ```
>         layers = [nn.Linear(n_inputs, n_units[0])]
>         for i in range(n_layers-1):
>             layers.append(nonlinear())
>             layers.append(nn.Linear(n_units[i], n_units[i+1]))
>         layers.append(nonlinear())
>         layers.append(nn.Linear(n_units[-1], n_outputs))
>         self.layers = nn.Sequential(*layers)
> ```

That's Cool. I really appreciate it.
